import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { auth, signOut } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  async function handleSignOut() {
    "use server";
    await signOut({ redirectTo: "/" });
  }

  return (
    <html lang="ko">
      <body style={{ padding: '0 20px', maxWidth: '800px', margin: '0 auto' }}>
        <header style={{ display: 'flex', justifyContent: 'space-between', padding: '20px 0', borderBottom:'1px solid #ddd' }}>
          <Link href="/" style={{ fontWeight: 'bold', textDecoration: 'none' }}>
            🚀 AUTH BLOG
          </Link>

          <div style={{ display: 'flex', alignItems: 'center', gap: '15px' }}>

            {session ? 
                (
                <>
                  <span><b>{session.user?.name}</b></span>
                  <form action={handleSignOut}>
                    <button type="submit">로그아웃</button>
                  </form>
                </>
                )
                :
                (
                  <Link href="/api/auth/signin">로그인하기</Link>
                )
            }
            </div>
            </header>
            <main style={{ padding: '20px 0' }}>{children}</main>
        </body>
    </html>
  );
}
